[colors.primary]
background = "#1b1e28"
foreground = "#f2f2f2"

[colors.cursor]
text = "CellForeground"
cursor = "#c2c8d6"

[colors.selection]
text = "CellForeground"
background = "#333b4c"

[colors.normal]
black = "#667599"
red = "#e87d7d"
green = "#7de892"
yellow = "#e8cb7d"
blue = "#7d98e8"
magenta = "#c47de8"
cyan = "#7dd6e8"
white = "#c2c8d6"

[colors.bright]
black = "#667599"
red = "#e87d7d"
green = "#7de892"
yellow = "#e8cb7d"
blue = "#7d98e8"
magenta = "#c47de8"
cyan = "#7dd6e8"
white = "#c2c8d6"
